# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['app', 'hops', 'BinaryMultiply', 'components', 'get_components']

# %% ../app.ipynb 1
from flask import Flask
import ghhops_server as hs
import rhino3dm

# %% ../app.ipynb 2
# register hops app as middleware
app = Flask(__name__)
hops: hs.HopsFlask = hs.Hops(app)

# %% ../app.ipynb 3
# float multiplication
@hops.component(
    "/binmult",
    inputs=[hs.HopsNumber("A"), hs.HopsNumber("B")],
    outputs=[hs.HopsNumber("Multiply")],
)
def BinaryMultiply(a: float, b: float):
    return a * b

# %% ../app.ipynb 4
def components():
    local_ip = 'http://127.0.0.1:5000'
    component_list = [f'{local_ip + k}' for k, v in hops._components.items()]
    return component_list

# %% ../app.ipynb 5
@hops.component(
    "/component_list",
    outputs=[hs.HopsString(f'{x}') for x in components()]
)
def get_components():
    return components()

# %% ../app.ipynb 7
# run flask app
if __name__ == '__main__':
    app.run()
